steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - >-
        asia-northeast3-docker.pkg.dev/$_GCP_PROJECT_ID/$_GCP_PROJECT_ID-docker-registry/sbn-datainfra-youtube-cookie-manager:$COMMIT_SHA
      - -t
      - asia-northeast3-docker.pkg.dev/$_GCP_PROJECT_ID/$_GCP_PROJECT_ID-docker-registry/sbn-datainfra-youtube-cookie-manager:latest
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia-northeast3-docker.pkg.dev/$_GCP_PROJECT_ID/$_GCP_PROJECT_ID-docker-registry/sbn-datainfra-youtube-cookie-manager:$COMMIT_SHA
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia-northeast3-docker.pkg.dev/$_GCP_PROJECT_ID/$_GCP_PROJECT_ID-docker-registry/sbn-datainfra-youtube-cookie-manager:latest
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - gcloud
      - run
      - jobs
      - deploy
      - cookie-manager
      - --image
      - asia-northeast3-docker.pkg.dev/$_GCP_PROJECT_ID/$_GCP_PROJECT_ID-docker-registry/sbn-datainfra-youtube-cookie-manager:latest
      - --region
      - asia-northeast3
      - --set-env-vars=project_id=$_GCP_PROJECT_ID
      - --set-env-vars=secret_id_account=$_GCP_SECRET_ID_ACCOUNT
      - --set-env-vars=secret_id_cookies=$_GCP_SECRET_ID_COOKIES